### ISSUE TITLE
Bitcoin directory contains references to Elements

### ISSUE THREAD

**Issue by ysangkok** [ElementsProject/simplicity#16]
Are these comments correct? I think they should say Bitcoin instead of Elements.

```
janus@janus-UX305CA ~/simplicity/Haskell/Simplicity/Bitcoin
 % ack Elements
Programs/CheckSigHashAll/Lib.hs
2:-- | This module unpacks the 'Simplicity.Elements.Programs.CheckSigHashAll.libCore' and 'Simplicity.Elements.Programs.CheckSigHashAll.libAssert' library instances into individual functions.
3:-- Users should prefer to use 'Simplicity.Elements.Programs.CheckSigHashAll.mkLibCore' and 'Simplicity.Elements.Programs.CheckSigHashAll.mkLibAssert' in order to share library dependencies.

Programs/CheckSigHashAll.hs
103:-- | An instance of the Elements checkSigHash 'Lib' library.
```

**Comment by ysangkok** [comment]
also, `Programs/CheckSigHashAll/Lib.hs` contains references to `mkLibCore` and `mkLibAssert`, but they are not defined, not even in Elements.

    Users should prefer to use 'Simplicity.Elements.Programs.CheckSigHashAll.mkLibCore' and 'Simplicity.Elements.Programs.CheckSigHashAll.mkLibAssert' in order to share library dependencies.

**Comment by roconnor-blockstream** [comment]
Fixed in https://github.com/ElementsProject/simplicity/commit/26750067dfc7706f11b25959bf91c2470e9cad5f
