### ISSUE TITLE
Renamed jets

### ISSUE THREAD

**Issue by uncomputable** [ElementsProject/simplicity#212]
The tech report and wiki include the following jets (in front of arrow), but the code base renamed them (after arrow).

- tap-leaf-hash → tapleaf-hash
- tapbranch → tappath
- tapbranch-hash → tappath-hash
- input-asset-amounts-hash → input-amounts-hash
    - _issuance-asset-amounts-hash was not renamed_
- output-asset-amounts-hash -> output-amounts-hash

There may be more inconsistencies related to tap paths and asset amounts.

**Comment by roconnor-blockstream** [comment]
The Tech Report seems fine to me.

**Comment by uncomputable** [comment]
I was using a tech report from one year ago; oops.

Most of the jet names have been fixed. However, it's still `tap-leaf-hash` in the tech report and `tapleaf_hash` in the code.

`issuance-asset-amounts-hash` probably includes `asset` to differentiate it from `issuance-token-amounts-hash`. In that case, the longer name makes sense.

**Comment by roconnor-blockstream** [comment]
Additionally `bip0340-schnorr-verify` is written in the tech report; however the code uses `bip_0340_verify`

**Comment by roconnor-blockstream** [comment]
And `check-sig-verify` is missing from the tech report.

**Comment by roconnor-blockstream** [comment]
Fixed in 00f4c0f785d49f473b92c2a427b1aac1c8b00513
