### ISSUE TITLE
incorrect use of free

### ISSUE THREAD

**Issue by gmaxwell** [ElementsProject/simplicity#24]
https://github.com/ElementsProject/simplicity/blob/master/C/primitive/elements.c#L494

if type inference fails, it can free type_dag even though it is not allocated. Also, checking type_dag for nullness in that short-cutting and cascade isn't kosher because it could be uninitialized.

**Comment by gmaxwell** [comment]
The early returns above there can also fail to deallocate dag.

**Comment by roconnor-blockstream** [comment]
The [post-condition for `mallocTypeInference`](https://github.com/ElementsProject/simplicity/blob/4ff3395b0b64d446bb5876e5928881d90d14f24b/C/typeInference.c#L598) says that `type_dag` is supposed to be set to `NULL` if the function returns `false`.  However this post-condition doesn't appear to be properly enforced, so `mallocTypeInference` needs to be fixed.

**Comment by roconnor-blockstream** [comment]
The memory leaks of through the early returns are a problem.

**Comment by roconnor-blockstream** [comment]
`decodeMallocWitnessData` has the same sort of problem.  It is required to set `allocation` to NULL when returning a negative value, but the implementation doesn't always ensure this.
