### ISSUE TITLE
Size zero VLAs in sizeof()

### ISSUE THREAD

**Issue by gmaxwell** [ElementsProject/simplicity#25]
>   /* MOVE_FRAME */
>  memmove( state.activeReadFrame->edge, state.activeWriteFrame->edge
>    , sizeof(UWORD[(state.activeWriteFrame + 1)->edge - state.activeWriteFrame->edge])

UBSan happens to believe that this is undefined behaviour when the size of that VLA is 0. Using a VLA like that in a sizeof instead of just explicitly multiplying the size isn't particularly idiomatic, so this isn't a case I'd ever considered before.

If it is valid then at a minimum it's likely to trigger spurious warnings in analysis tools.

**Comment by roconnor-blockstream** [comment]
I've been planning to entirely remove VLA from the codebase (they are mostly used in `sizeof` operations currently).  Now that it is causing a bug, I'll do this sooner rather than later.

**Comment by roconnor-blockstream** [comment]
For the record, https://github.com/ElementsProject/simplicity/blob/7d6c63da0fd57df9ea2bcce3922941bbb7e3f170/C/typeInference.c#L605 is another example where, for degenerate inputs, a zero sized VLA could occur.

**Comment by roconnor-blockstream** [comment]
Should be fixed by https://github.com/ElementsProject/simplicity/pull/28/commits/921e69cf673cd0314402ed4b2f36dfa70545c144.
