### ISSUE TITLE
Haskell base 4.14 compatibility

### ISSUE THREAD

**Issue by ysangkok** [ElementsProject/simplicity#47]
GHC 8.10 which is now released uses base 4.14 which is currently excluded in the Cabal file. I made the change to 4.15 and everything seems to work fine.

**Comment by roconnor-blockstream** [comment]
Last time I tried GHC 8.10, it consumed all my memory when building the static analysis tests before OMM killer killed the compiler.

Really, I ought to rewrite or disable the particular test causing the issue, though I'm tempted to try to track down which optimization is causing the problem.

**Comment by roconnor-blockstream** [comment]
I believe I have now identified the source of the memory issues when compiling the static analysis tests, and I'll be rolling out a workaround.

For those curious about the nature of the problem, the test requires an `Arbitrary` instance of `(Word256, Word512)` which, when you expand the types is a deeply nested tuple containing 768 instances of `Either () ()`.  While this sort of type doesn't appear to cause serious problems elsewhere in the Simplicity library, the GHC Simplifier here seems to be duplicating the arbitrary instance for `Either () ()` 768 time, and all the pairs of those Either instances, and the pairs of those pairs, etc.

**Comment by roconnor-blockstream** [comment]
Fixed in 23626323d19d6b996a16c4d9e01c6cbc5610aef7.
