### ISSUE TITLE
README file needs to update the VST link to 2.5

### ISSUE THREAD

**Issue by matthewjablack** [ElementsProject/simplicity#57]
Came across this issue while trying to build the Simplicity project without Nix `make -f CoqMakefile`

```
COQC Simplicity/SHA256.v
File "./Simplicity/SHA256.v", line 337, characters 8-23:
Error: The reference Zbits.eqmod_mod was not found in the current
environment.

make[1]: *** [Simplicity/SHA256.vo] Error 1
make: *** [all] Error 2
```

**Comment by matthewjablack** [comment]
I'm assuming this is a typo where 

`apply Zbits.eqmod_mod` should be `apply Int.eqmod_mod`

**Comment by roconnor-blockstream** [comment]
This was explicitly changed in 

https://github.com/ElementsProject/simplicity/commit/872c7350ed2e1df7daa667d5540221d140a650bb#diff-129c372828b98dde12c4875f5dc8b9b4

When migrating to VST 2.5

The real error is that I didn't update the README file.

**Comment by roconnor-blockstream** [comment]
Fixed in https://github.com/ElementsProject/simplicity/commit/91dbc983fc1d10e460af0b0abe517d3df20cb54d.
