### ISSUE TITLE
Release lens-family-core 2.0.0 to make building with mainstream build systems easier

### ISSUE THREAD

**Issue by ysangkok** [ElementsProject/simplicity#8]
While Nix is great, I don't have a lot of HDD space left, so I wanna stick with my existing toolchain. But I tried creating a stack configuration, but it seems like it is failing because Simplicity requires lens-family-core 2.0.0, which hasn't been released and as such hasn't gotten into Stackage.

I notice that development of the Haskell libraries seems to have settled a bit, so maybe, if it was possible, would it be possible to release dependencies like lens-family-core with a version number? That would make it a lot easier for me to build.

Thanks.

**Comment by roconnor-blockstream** [comment]
Thanks for your interest.  The documentation for lens-family-core 2.0.0 isn't completed yet which is holding up the release.  I have a personal due date of 2019-07-19 to have it completed by.  Until then you should be able to grab a pre-release version from <https://hub.darcs.net/roconnor/lens-family/dist>. I'm not familiar with Stack, but you should be able to build lens-family-core from those sources and then build the Simplicity Haskell library.

**Comment by ysangkok** [comment]
This was fixed on Fri Jul 19 14:43:30 UTC 2019 according to Hackage.
